version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    commit-message:
      prefix: "deps(npm)"
    schedule:
      interval: weekly
      day: sunday
    assignees:
  - package-ecosystem: bundler
    directory: "/"
    commit-message:
      prefix: "deps(bundler)"
    schedule:
      interval: weekly
      day: sunday
    assignees:
