version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
    assignees:
      - malteo
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
    assignees:
      - malteo
