version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    commit-message:
      prefix: "chore(npm)"
    schedule:
      interval: weekly
      day: sunday
    assignees:
      - malteo
  - package-ecosystem: bundler
    directory: "/"
    commit-message:
      prefix: "chore(bundler)"
    schedule:
      interval: weekly
      day: sunday
    assignees:
      - malteo
