version: 2

updates:
- package-ecosystem: npm
  directory: "/website"
  schedule:
    interval: weekly
  reviewers:
  - malteo

- package-ecosystem: "bundler"
  directory: "/"
  schedule:
    interval: "weekly"
  reviewers:
  - malteo
