version: 2.1

orbs:
  cloudesire: cloudesire/common@dev:b6d80ca

jobs:
  build:
    docker:
      - image: cimg/node:16.0
    resource_class: small

    steps:
      - checkout

      - cloudesire/git_merge_default

      - restore_cache:
          name: Restore cache
          keys:
            - yarn-packages-v1-{{ checksum "website/yarn.lock" }}

      - run:
          name: Fetch dependencies
          command: cd website && yarn install

      - save_cache:
          name: Save cache
          key: yarn-packages-v1-{{ checksum "website/yarn.lock" }}
          paths:
            - website/node_modules/

      - run:
          name: Build
          command: cd website && yarn build

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - .

  verify:
    docker:
      - image: cimg/ruby:2.7
    resource_class: small

    steps:
      - attach_workspace:
          at: /home/circleci/project

      - restore_cache:
          name: Restore cache
          keys:
            - bundle-v2-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install bundler
          command: gem install bundler

      - run:
          name: Fetch dependencies
          command: bundle install

      - save_cache:
          name: Save cache
          key: bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Test markdown
          command: bundle exec mdl -s mdl-rules.rb docs
          when: always

      - run:
          name: Test html output
          command: bundle exec htmlproofer ./website/build/docusaurus --check-html --empty-alt-ignore --allow-hash-href --assume-extension --check-img-http --url-ignore '/github.com/ClouDesire/docusaurus/edit/source/' --url-ignore '/twitter.com/'
          when: always

  deploy:
    docker:
      - image: cimg/node:16.0
    resource_class: small

    steps:
      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: Configure GIT for pushing
          command: |
            git config --global user.email "cloudesire@users.noreply.github.com"
            git config --global user.name "CircleCI"
            echo "machine github.com login gionn password $GITHUB_TOKEN" > ~/.netrc

      - run:
          name: Deploy
          command: |
            cd website
            GIT_USER=gionn yarn run publish-gh-pages

workflows:
  version: 2
  docusaurus:
    jobs:
      - build
      - verify:
          requires:
            - build
      - deploy:
          requires:
            - verify
          filters:
            branches:
              only: source
