version: 2
jobs:
  deploy-website:
    docker:
      - image: circleci/node:7.10

    steps:
      - checkout
      - run: 
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "cloudesire@users.noreply.github.com"
            git config --global user.name "CircleCI"
            echo "machine github.com login gionn password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=gionn yarn run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
          filters:
            branches:
              only: source
