version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - run:
          name: Configure GIT for pushing
          command: |
            git config --global user.email "cloudesire@users.noreply.github.com"
            git config --global user.name "CircleCI"
            echo "machine github.com login gionn password $GITHUB_TOKEN" > ~/.netrc

      - restore_cache:
          name: Restore cache
          keys:
            - yarn-packages-v1-{{ checksum "website/yarn.lock" }}

      - run:
          name: Fetch dependencies
          command: cd website && yarn install

      - save_cache:
          name: Save cache
          key: yarn-packages-v1-{{ checksum "website/yarn.lock" }}
          paths:
            - website/node_modules/

      - run:
          name: Build or deploy
          command: |
            cd website
            if [ "$CIRCLE_BRANCH" == "source" ]; then
              GIT_USER=gionn yarn run publish-gh-pages
            else
              yarn build
            fi

