version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    steps:
      - checkout

      - restore_cache:
          name: Restore cache
          keys:
            - yarn-packages-v1-{{ checksum "website/yarn.lock" }}

      - run:
          name: Fetch dependencies
          command: cd website && yarn install

      - save_cache:
          name: Save cache
          key: yarn-packages-v1-{{ checksum "website/yarn.lock" }}
          paths:
            - website/node_modules/

      - run:
          name: Build
          command: cd website && yarn build
      
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - .

  verify:
    docker:
      - image: circleci/ruby:2.3

    steps:
      - attach_workspace:
          at: /home/circleci/project

      - restore_cache:
          name: Restore cache
          keys:
            - bundle-v2-{{ checksum "Gemfile.lock" }}

      - run:
          name: Fetch dependencies
          command: bundle install --path vendor/bundle

      - save_cache:
          name: Save cache
          key: bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Test
          command: bundle exec htmlproofer ./website/build --check-html --disable-external --empty-alt-ignore --allow-hash-href --assume-extension
  
  deploy:
    docker:
      - image: circleci/node:8

    steps:
      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: Configure GIT for pushing
          command: |
            git config --global user.email "cloudesire@users.noreply.github.com"
            git config --global user.name "CircleCI"
            echo "machine github.com login gionn password $GITHUB_TOKEN" > ~/.netrc

      - run:
          name: Deploy
          command: |
            cd website
            GIT_USER=gionn yarn run publish-gh-pages

workflows:
  version: 2
  docusaurus:
    jobs:
      - build
      - verify:
          requires:
            - build
      - deploy:
          requires:
            - verify
          filters:
            branches:
              only: source